let currentLang = 'ja';

const LANG = {
    ja: {
        yes: 'はい',
        no: 'いいえ',
        lang_ja: '日本語',
        lang_en: 'English',
        phase: 'フェーズ',
        score: 'スコア',
        combo_label: 'COMBO',
        streak: 'Streak',
        fever: 'FEVER',
        cd: '準備中',
        sec: 's',
        start_title: 'コンボローグストライク',
        start_sub: 'タイミングよく撃て！',
        select_mode: 'モードを選べ',
        mode_std: 'Standard',
        mode_std_desc: '10フェーズ 標準難易度',
        mode_hard: 'Hard',
        mode_hard_desc: '10フェーズ<br>超速タイミング・小型',
        mode_endless: 'Endless',
        mode_endless_desc: '上限なし スコアアタック',
        ranking: 'ランキング',
        stats: '累計統計',
        achievements: '実績',
        settings: '設定',
        tutorial: 'チュートリアル',
        hs_std: 'Standard',
        hs_hard: 'Hard',
        hs_endless: 'Endless',
        controls_hint: 'Space / Enter / 左クリック: 攻撃 &nbsp;|&nbsp; Esc: ポーズ',
        mobile_hint: '📱 タップ: 攻撃 &nbsp;|&nbsp; ⏸: ポーズ',
        tablet_note: '※タブレットはレイアウト編集推奨 &nbsp;|&nbsp; スマホ非対応',
        version: 'v1.0.0',
        tutorial_title: 'チュートリアル',
        ctrl_title: '操作',
        ctrl_1: 'Space / Enter / 左クリック → 攻撃（マウス位置のターゲットを狙う）',
        ctrl_2: 'Esc → ポーズ',
        judge_title: '判定',
        judge_perfect: 'Perfect (<span class="t-gold">×1.5</span>) → リングが重なるタイミング',
        judge_good: 'Good (<span class="t-white">×1.0</span>)',
        judge_ok: 'OK (<span class="t-blue">×0.6</span>)',
        judge_early: 'Early (ダメージ0)',
        sys_title: 'システム',
        sys_1: 'コンボを繋ぐ → ダメージ増加',
        sys_2: '15コンボ → FEVER発動（30秒間スコア2倍）',
        sys_3: '色付きターゲット（紫/金/赤）が出現',
        sys_4: 'フェーズクリア → 強化を選択',
        close: '閉じる',
        pause_title: '一時停止中',
        resume: '再開',
        tab_upgrades: '強化',
        tab_settings: '設定',
        paused_no_upgrades: 'まだ強化なし',
        retire: 'リタイア',
        retire_confirm: 'リタイアしますか？',
        vol_label: '音量',
        shake_label: '画面揺れ',
        shake_strong: '強',
        shake_weak: '弱',
        shake_off: '切',
        layout_edit: 'レイアウト編集',
        settings_title: '設定',
        settings_clear: 'データをすべて消去',
        clear_confirm: 'ハイスコア・累計統計・実績・設定・レイアウトをすべて消去します。よろしいですか？',
        clear_confirm2: '本当に消去しますか？この操作は元に戻せません。',
        settings_close: '閉じる',
        ranking_title: 'ランキング',
        ranking_loading: '読み込み中...',
        ranking_empty: 'まだデータがありません',
        ranking_close: '閉じる',
        stats_title: '累計統計',
        stat_plays: '総プレイ回数',
        stat_hits: '総ヒット数',
        stat_score_total: '総スコア',
        stat_time: '総プレイ時間',
        stat_best_combo: '最高コンボ',
        stat_best_streak: '最高ストリーク',
        stats_close: '閉じる',
        ach_title: '実績',
        ach_close: '閉じる',
        ach_unlock: '実績解除!',
        result_title_clear: 'ゲームクリア！',
        result_title_retire: 'リタイア',
        result_title_gameover: 'Game Over',
        result_mode: 'モード',
        result_phase: 'フェーズ',
        result_new_record: '★ ニューレコード!',
        result_highscore: 'ハイスコア',
        result_name_label: '名前',
        result_name_placeholder: '名無し',
        result_name_default: '名無し',
        result_rank_submit: 'ランキングに送信',
        result_rank_noupdate: 'ハイスコア更新なし',
        result_rank_sent: '送信しました！',
        result_rank_section: 'ランキング',
        result_myrank: 'あなたの順位',
        result_rank: '位',
        result_dmg_total: '合計ダメ',
        result_detail_toggle: '[詳細▼]',
        result_detail_toggle_up: '[詳細▲]',
        result_dmg_title: 'ダメージ内訳',
        result_base: '基本',
        result_crit: 'クリティカル',
        result_ds: '連撃',
        result_echo: 'エコー',
        result_lucky: 'ラッキー',
        result_streak: 'ストリーク',
        result_score_title: 'スコア内訳',
        result_dmg_score: '与ダメ',
        result_fever: 'フィーバー',
        result_chain: 'チェイン',
        result_absorb: '吸収',
        result_finisher: 'フィニッシャー',
        stat_perfect: 'Perfect',
        stat_good: 'Good',
        stat_ok: 'OK',
        stat_miss: 'Miss',
        stat_early: 'Early',
        stat_accuracy: '精度',
        stat_max_combo: '最大コンボ',
        stat_max_streak: '最大ストリーク',
        stat_blue: '🟦青',
        stat_purple: '🟪紫',
        stat_gold: '🟨金',
        stat_red: '🟥赤',
        result_upgrades: '取得強化',
        result_none: 'なし',
        btn_restart: 'もう一度',
        btn_tweet: 'X(旧Twitter)で共有',
        btn_title: 'タイトルに戻る',
        choice_header: '選択肢',
        boss_choice_header: 'ボス撃破! 2つ選べ',
        log_start_std: '【Standard】開始！',
        log_start_hard: '【Hard】開始！',
        log_start_endless: '【Endless】開始！',
        msg_start_std: '10フェーズ 標準難易度',
        msg_start_hard: '10フェーズ 超速タイミング',
        msg_start_endless: '上限なし スコアアタック',
        log_perfect: 'Perfect! {0}ダメージ コンボ{1}{2}',
        log_good: '{0}ダメージ コンボ{1}{2}',
        log_ok: '{0}ダメージ コンボ{1}{2}',
        log_early: 'Early! ダメージなし',
        log_miss_barrier: '障壁発動! 残り{0}回',
        log_miss_safe: 'Miss... コンボ-{0}',
        log_miss_reset: 'Miss... コンボリセット',
        log_crit: 'クリティカル!',
        log_streak: '＋{0} ストリークボーナス!',
        log_chain: 'チェインボーナス +{0}',
        log_ds: '連撃! x{0} +{1}',
        log_lucky: '🍀 ラッキー!',
        log_echo: 'エコー! +{0}',
        log_combo_50: '⚡ 50コンボ!',
        log_combo_75: '75コンボ!',
        log_combo_100: '🔥 100コンボ!',
        log_combo_100plus: '🔥 {0}コンボ!',
        log_combo_10: '10コンボ!',
        log_combo_5: '5コンボ!',
        log_fever: '🔥 FEVER! 30秒間スコア2倍',
        log_phase_clear: 'フェーズ{0}クリア！',
        log_boss_hint: '⚠ 次はボスフェーズ (Phase {0})！',
        log_phase_start: 'フェーズ{0}開始',
        text_phase_clear: 'フェーズ{0}クリア！',
        text_boss_clear: 'ボス撃破! 2つ選べ',
        text_choose: '選択肢を選んでください',
        text_phase_start: 'フェーズ{0}開始！',
        text_phase_new: 'フェーズ{0}開始！',
        log_choice_done: '選択肢決定',
        log_absorb: '吸収ボーナス +{0}',
        log_finisher: 'フィニッシャー +{0}',
        log_retire: 'リタイア 最終スコア: {0}',
        log_clear: 'ゲームクリア！最終スコア: {0}',
        perfect: 'Perfect!',
        good: 'Good',
        ok: 'OK',
        early: 'Early',
        streak_text: '{0} Streak',
        streak_2: 'あと1!',
        streak_3: '3連続! +50%',
        streak_5: '5連続! +100%',
        streak_10: '10連続! +150%',
        streak_20: '20連続! +200%',
        streak_30: '30連続! +250%',
        streak_50: '50連続! +300%',
        streak_75: '75連続! +350%',
        streak_100: '100連続! +400%',
        streak_custom: '{0}連続! +{1}%',
        loading: '読み込み中...',
        rank_loading: '読み込み中...',
        rank_empty: 'まだデータがありません',
        rank_no_data: 'まだデータがありません',
        ach_popup_title: '実績解除!',
        upgrade_attack: '攻撃力UP',
        upgrade_attack_desc: '与ダメージ+25%',
        upgrade_crit: 'クリティカル',
        upgrade_crit_desc: '10%の確率で3倍ダメージ（重ねると段階的強化）',
        upgrade_combo: 'コンボ倍率UP',
        upgrade_combo_desc: 'コンボ倍率ベース+0.1（取得は1回のみ）',
        upgrade_size: 'ターゲット拡大',
        upgrade_size_desc: 'ターゲットの半径+15%（取得は2回まで）',
        upgrade_time: '余裕UP',
        upgrade_time_desc: 'ターゲットが消えるまでの時間+20%（取得は2回まで）',
        upgrade_score: 'スコアブースト',
        upgrade_score_desc: '獲得スコア+30%',
        upgrade_safe: 'コンボセーフ',
        upgrade_safe_desc: 'ミス時のコンボ減少を3軽減（重ねると軽減量増加）',
        upgrade_chain: 'チェイン',
        upgrade_chain_desc: '5コンボ達成ごとに250ポイント（Perfect時のみ）（取得は1回のみ）',
        upgrade_lucky: 'ラッキー',
        upgrade_lucky_desc: '10%の確率でフェーズ×100の追加ダメージ（取得は1回のみ）',
        upgrade_finisher: 'フィニッシャー',
        upgrade_finisher_desc: 'フェーズクリア時にフェーズ×15スコア加算',
        upgrade_ds: '連撃',
        upgrade_ds_desc: '15%の確率でダメージ2倍（重ねると段階的強化）',
        upgrade_absorb: '吸収',
        upgrade_absorb_desc: '敵撃破時に+200スコア（取得は1回のみ）',
        upgrade_echo: 'エコー',
        upgrade_echo_desc: '20%の確率で100%追加ダメージ（取得は2回まで）',
        upgrade_barrier: '障壁',
        upgrade_barrier_desc: 'ミスを1回無効化（使い切り、重ねると回数増加）',
        upgrade_aura: 'オーラ',
        upgrade_aura_desc: '10コンボごとに+1.5（例:30コンボで+4.5）',
        ach_1: '初プレイ',
        ach_1_desc: 'ゲームを1回プレイ',
        ach_2: 'コンボ10',
        ach_2_desc: 'コンボ10達成',
        ach_3: 'コンボ50',
        ach_3_desc: 'コンボ50達成',
        ach_4: 'コンボ100',
        ach_4_desc: 'コンボ100達成',
        ach_5: 'ストリーク10',
        ach_5_desc: 'Perfectストリーク10達成',
        ach_6: 'ストリーク30',
        ach_6_desc: 'Perfectストリーク30達成',
        ach_7: 'FEVER!',
        ach_7_desc: '初めてFEVER発動',
        ach_8: 'ボス撃破',
        ach_8_desc: '初めてボスを倒す',
        ach_9: 'Standardクリア',
        ach_9_desc: 'Standardモードクリア',
        ach_10: 'Hardクリア',
        ach_10_desc: 'Hardモードクリア',
        ach_11: 'スコア10000',
        ach_11_desc: '1回のプレイで10000点達成',
        ach_12: 'スコア50000',
        ach_12_desc: '1回のプレイで50000点達成',
        ach_13: '全モードクリア',
        ach_13_desc: 'Standard + Hard両方クリア',
        ach_14: '強化コレクター',
        ach_14_desc: '15種全ての強化を獲得',
        ach_15: 'パーフェクトラウンド',
        ach_15_desc: '1フェーズを全Perfectでクリア',
        min_format: '{0}分{1}秒',
        share_text: 'コンボローグストライク\n{0} モード {1}点！\n到達フェーズ: {2}\n\n#コンボローグストライク',
        target_blue: 'blue',
        target_purple: 'purple',
        target_gold: 'gold',
        target_red: 'red',
    },
    en: {
        yes: 'Yes',
        no: 'No',
        lang_ja: '日本語',
        lang_en: 'English',
        phase: 'Phase',
        score: 'Score',
        combo_label: 'COMBO',
        streak: 'Streak',
        fever: 'FEVER',
        cd: 'Cooldown',
        sec: 's',
        start_title: 'Combo Rogue Strike',
        start_sub: 'Timing is everything!',
        select_mode: 'Select Mode',
        mode_std: 'Standard',
        mode_std_desc: '10 Phases - Standard',
        mode_hard: 'Hard',
        mode_hard_desc: '10 Phases<br>Fast timing, small targets',
        mode_endless: 'Endless',
        mode_endless_desc: 'No limit - Score Attack',
        ranking: 'Ranking',
        stats: 'Statistics',
        achievements: 'Achievements',
        settings: 'Settings',
        tutorial: 'Tutorial',
        hs_std: 'Standard',
        hs_hard: 'Hard',
        hs_endless: 'Endless',
        controls_hint: 'Space / Enter / Left Click: Attack &nbsp;|&nbsp; Esc: Pause',
        mobile_hint: '📱 Tap: Attack &nbsp;|&nbsp; ⏸: Pause',
        tablet_note: '※ Tablet layout is editable &nbsp;|&nbsp; Smartphones not supported',
        version: 'v1.0.0',
        tutorial_title: 'Tutorial',
        ctrl_title: 'Controls',
        ctrl_1: 'Space / Enter / Left Click → Attack (aim at target)',
        ctrl_2: 'Esc → Pause',
        judge_title: 'Judgment',
        judge_perfect: 'Perfect (<span class="t-gold">×1.5</span>) → Hit when the ring aligns',
        judge_good: 'Good (<span class="t-white">×1.0</span>)',
        judge_ok: 'OK (<span class="t-blue">×0.6</span>)',
        judge_early: 'Early (No damage)',
        sys_title: 'System',
        sys_1: 'Chain combos → Damage increases',
        sys_2: '15 Combo → FEVER (2x score for 30s)',
        sys_3: 'Colored targets (Purple/Gold/Red) appear',
        sys_4: 'Clear phases → Choose upgrades',
        close: 'Close',
        pause_title: 'PAUSED',
        resume: 'Resume',
        tab_upgrades: 'Upgrades',
        tab_settings: 'Settings',
        paused_no_upgrades: 'No upgrades yet',
        retire: 'Retire',
        retire_confirm: 'Retire?',
        vol_label: 'Volume',
        shake_label: 'Screen Shake',
        shake_strong: 'Strong',
        shake_weak: 'Weak',
        shake_off: 'Off',
        layout_edit: 'Layout Editor',
        settings_title: 'Settings',
        settings_clear: 'Clear All Data',
        clear_confirm: 'Clear all high scores, statistics, achievements, settings and layouts?',
        clear_confirm2: 'This cannot be undone. Continue?',
        settings_close: 'Close',
        ranking_title: 'Ranking',
        ranking_loading: 'Loading...',
        ranking_empty: 'No data yet',
        ranking_close: 'Close',
        stats_title: 'Statistics',
        stat_plays: 'Total Plays',
        stat_hits: 'Total Hits',
        stat_score_total: 'Total Score',
        stat_time: 'Total Play Time',
        stat_best_combo: 'Best Combo',
        stat_best_streak: 'Best Streak',
        stats_close: 'Close',
        ach_title: 'Achievements',
        ach_close: 'Close',
        ach_unlock: 'Achievement Unlocked!',
        result_title_clear: 'Game Clear!',
        result_title_retire: 'Retired',
        result_title_gameover: 'Game Over',
        result_mode: 'Mode',
        result_phase: 'Phase',
        result_new_record: '★ New Record!',
        result_highscore: 'High Score',
        result_name_label: 'Name',
        result_name_placeholder: 'Anonymous',
        result_name_default: 'Anonymous',
        result_rank_submit: 'Submit to Ranking',
        result_rank_noupdate: 'No new high score',
        result_rank_sent: 'Submitted!',
        result_rank_section: 'Ranking',
        result_myrank: 'Your Rank',
        result_rank: 'th',
        result_dmg_total: 'Total DMG',
        result_detail_toggle: '[Details▼]',
        result_detail_toggle_up: '[Details▲]',
        result_dmg_title: 'Damage Breakdown',
        result_base: 'Base',
        result_crit: 'Critical',
        result_ds: 'Double Strike',
        result_echo: 'Echo',
        result_lucky: 'Lucky',
        result_streak: 'Streak',
        result_score_title: 'Score Breakdown',
        result_dmg_score: 'From Damage',
        result_fever: 'Fever',
        result_chain: 'Chain',
        result_absorb: 'Absorb',
        result_finisher: 'Finisher',
        stat_perfect: 'Perfect',
        stat_good: 'Good',
        stat_ok: 'OK',
        stat_miss: 'Miss',
        stat_early: 'Early',
        stat_accuracy: 'Accuracy',
        stat_max_combo: 'Max Combo',
        stat_max_streak: 'Max Streak',
        stat_blue: '🟦Blue',
        stat_purple: '🟪Purple',
        stat_gold: '🟨Gold',
        stat_red: '🟥Red',
        result_upgrades: 'Upgrades',
        result_none: 'None',
        btn_restart: 'Retry',
        btn_tweet: 'Share on X',
        btn_title: 'Back to Title',
        choice_header: 'Choose',
        boss_choice_header: 'Boss Down! Pick 2',
        log_start_std: '[Standard] Started!',
        log_start_hard: '[Hard] Started!',
        log_start_endless: '[Endless] Started!',
        msg_start_std: '10 Phases - Standard',
        msg_start_hard: '10 Phases - Fast Timing',
        msg_start_endless: 'No limit - Score Attack',
        log_perfect: 'Perfect! {0} dmg Combo {1}{2}',
        log_good: '{0} dmg Combo {1}{2}',
        log_ok: '{0} dmg Combo {1}{2}',
        log_early: 'Early! No damage',
        log_miss_barrier: 'Barrier! {0} charges left',
        log_miss_safe: 'Miss... Combo -{0}',
        log_miss_reset: 'Miss... Combo reset',
        log_crit: 'Critical!',
        log_streak: '+{0} Streak Bonus!',
        log_chain: 'Chain Bonus +{0}',
        log_ds: 'Double Strike! x{0} +{1}',
        log_lucky: '🍀 Lucky!',
        log_echo: 'Echo! +{0}',
        log_combo_50: '⚡ 50 Combo!',
        log_combo_75: '75 Combo!',
        log_combo_100: '🔥 100 Combo!',
        log_combo_100plus: '🔥 {0} Combo!',
        log_combo_10: '10 Combo!',
        log_combo_5: '5 Combo!',
        log_fever: '🔥 FEVER! 2x Score for 30s',
        log_phase_clear: 'Phase {0} Clear!',
        log_boss_hint: '⚠ Boss next phase (Phase {0})!',
        log_phase_start: 'Phase {0} started',
        text_phase_clear: 'Phase {0} Clear!',
        text_boss_clear: 'Boss Down! Pick 2',
        text_choose: 'Choose your upgrade',
        text_phase_start: 'Phase {0} Start!',
        text_phase_new: 'Phase {0} Start!',
        log_choice_done: 'Upgrade chosen',
        log_absorb: 'Absorb Bonus +{0}',
        log_finisher: 'Finisher +{0}',
        log_retire: 'Retired - Final Score: {0}',
        log_clear: 'Game Clear! Final Score: {0}',
        perfect: 'Perfect!',
        good: 'Good',
        ok: 'OK',
        early: 'Early',
        streak_text: '{0} Streak',
        streak_2: 'One more!',
        streak_3: '3 Streak! +50%',
        streak_5: '5 Streak! +100%',
        streak_10: '10 Streak! +150%',
        streak_20: '20 Streak! +200%',
        streak_30: '30 Streak! +250%',
        streak_50: '50 Streak! +300%',
        streak_75: '75 Streak! +350%',
        streak_100: '100 Streak! +400%',
        streak_custom: '{0} Streak! +{1}%',
        loading: 'Loading...',
        rank_loading: 'Loading...',
        rank_empty: 'No data yet',
        rank_no_data: 'No data yet',
        ach_popup_title: 'Achievement Unlocked!',
        upgrade_attack: 'Attack Up',
        upgrade_attack_desc: 'Damage +25%',
        upgrade_crit: 'Critical',
        upgrade_crit_desc: '10% chance for 3x damage (stackable)',
        upgrade_combo: 'Combo Up',
        upgrade_combo_desc: 'Combo base +0.1 (once)',
        upgrade_size: 'Target Size Up',
        upgrade_size_desc: 'Target diameter +15% (2 times max)',
        upgrade_time: 'Extra Time',
        upgrade_time_desc: 'Spawn time +20% (2 times max)',
        upgrade_score: 'Score Boost',
        upgrade_score_desc: 'Score +30%',
        upgrade_safe: 'Combo Safe',
        upgrade_safe_desc: 'Miss reduces combo by 3 less (stackable)',
        upgrade_chain: 'Chain',
        upgrade_chain_desc: '250 pts every 5 combo (Perfect only, once)',
        upgrade_lucky: 'Lucky',
        upgrade_lucky_desc: '10% chance for phase x 100 bonus dmg (once)',
        upgrade_finisher: 'Finisher',
        upgrade_finisher_desc: 'Phase x 15 score on clear',
        upgrade_ds: 'Double Strike',
        upgrade_ds_desc: '15% chance for 2x damage (stackable)',
        upgrade_absorb: 'Absorb',
        upgrade_absorb_desc: '+200 score on enemy defeat (once)',
        upgrade_echo: 'Echo',
        upgrade_echo_desc: '20% chance for 100% bonus damage (2 times max)',
        upgrade_barrier: 'Barrier',
        upgrade_barrier_desc: 'Block 1 miss (consumable, stackable)',
        upgrade_aura: 'Aura',
        upgrade_aura_desc: '+1.5 every 10 combo (e.g. 30 combo = +4.5)',
        ach_1: 'First Play',
        ach_1_desc: 'Play the game 1 time',
        ach_2: 'Combo 10',
        ach_2_desc: 'Reach 10 combo',
        ach_3: 'Combo 50',
        ach_3_desc: 'Reach 50 combo',
        ach_4: 'Combo 100',
        ach_4_desc: 'Reach 100 combo',
        ach_5: 'Streak 10',
        ach_5_desc: 'Reach 10 Perfect streak',
        ach_6: 'Streak 30',
        ach_6_desc: 'Reach 30 Perfect streak',
        ach_7: 'FEVER!',
        ach_7_desc: 'Activate FEVER for the first time',
        ach_8: 'Boss Slayer',
        ach_8_desc: 'Defeat a boss for the first time',
        ach_9: 'Standard Clear',
        ach_9_desc: 'Clear Standard mode',
        ach_10: 'Hard Clear',
        ach_10_desc: 'Clear Hard mode',
        ach_11: 'Score 10000',
        ach_11_desc: 'Reach 10000 points in one play',
        ach_12: 'Score 50000',
        ach_12_desc: 'Reach 50000 points in one play',
        ach_13: 'All Modes Clear',
        ach_13_desc: 'Clear both Standard and Hard',
        ach_14: 'Upgrade Collector',
        ach_14_desc: 'Collect all 15 upgrades',
        ach_15: 'Perfect Round',
        ach_15_desc: 'Clear a phase with all Perfects',
        min_format: '{0}m {1}s',
        share_text: 'Combo Rogue Strike\n{0} Mode {1} pts!\nPhase: {2}\n\n#ComboRogueStrike',
        target_blue: 'blue',
        target_purple: 'purple',
        target_gold: 'gold',
        target_red: 'red',
    }
};

function t(key) {
    const text = LANG[currentLang][key];
    if (text === undefined) return key;
    return text;
}

function tf(key, ...args) {
    let text = LANG[currentLang][key];
    if (text === undefined) return key;
    args.forEach((arg, i) => text = text.replace(`{${i}}`, arg));
    return text;
}

function setLang(lang) {
    if (!LANG[lang]) return;
    currentLang = lang;
    try { localStorage.setItem('comboBattlerLang', lang); } catch (e) {}
    applyLang();
}

function applyLang() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        const val = t(key);
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            el.placeholder = val;
        } else {
            el.textContent = val;
        }
    });
    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        el.innerHTML = t(el.dataset.i18nHtml);
    });
    document.getElementById('lang-ja').classList.toggle('active', currentLang === 'ja');
    document.getElementById('lang-en').classList.toggle('active', currentLang === 'en');
    if (typeof updateCombatInfo === 'function') updateCombatInfo();
    if (typeof updateStreakDisplay === 'function') updateStreakDisplay();
    if (typeof updateInfoBar === 'function') updateInfoBar();
    if (typeof loadStats === 'function') loadStats();
}

(function initLang() {
    let saved = 'ja';
    try { saved = localStorage.getItem('comboBattlerLang') || 'ja'; } catch (e) {}
    currentLang = saved;
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', () => applyLang());
    } else {
        applyLang();
    }
})();
